<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWiywZK0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWiywZK0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWiywZK0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWiywZK0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWiywZK0\App_KernelDevDebugContainer([
    'container.build_hash' => 'WiywZK0',
    'container.build_id' => '165678c7',
    'container.build_time' => 1689149571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWiywZK0');
