<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKZj1UkC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKZj1UkC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKZj1UkC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKZj1UkC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKZj1UkC\App_KernelDevDebugContainer([
    'container.build_hash' => 'KZj1UkC',
    'container.build_id' => 'f53c41d7',
    'container.build_time' => 1689066642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKZj1UkC');
