<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQFJ7B3q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQFJ7B3q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQFJ7B3q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQFJ7B3q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQFJ7B3q\App_KernelDevDebugContainer([
    'container.build_hash' => 'QFJ7B3q',
    'container.build_id' => '701182ba',
    'container.build_time' => 1689069816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQFJ7B3q');
